name: Bug Report
description: Report a problem or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a detailed description of the issue you're encountering.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      placeholder: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What you expected to happen.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, app version...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: Any other information.
