name: Feature Request
description: Suggest a new idea or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your feature request or suggestion.

  - type: input
    id: feature
    attributes:
      label: Feature Summary
      placeholder: A short summary of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      placeholder: What problem does this feature solve?
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      placeholder: How could this feature be implemented?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: Any other notes or context.
